declare let AirCityPlayer: any;
declare let $: any;
// declare var userInfo: any;
declare let __g: {
  beam: any;
  callbackIndex: any;
  callbackMap: any;
  camera: any;
  cameraTour: any;
  cesium3DTileset: any;
  co: any;
  coord: any;
  ctag: any;
  customMesh: any;
  customObject: any;
  customTag: any;
  decal: any;
  dynamicWater: any;
  editHelper: any;
  eventCall: any;
  floodFill: any;
  fnLog: any;
  ha: any;
  heatmap: any;
  highlightArea: any;
  infoTree: any;
  isConnected: any;
  isFirstReady: any;
  layers: any;
  marker: any;
  misc: any;
  odline: any;
  onApiVersionReceived: any;
  onReadyCall: any;
  panorama: any;
  player: any;
  polygon: any;
  polygon3d: any;
  polyline: any;
  radiationPoint: any;
  rp: any;
  settings: any;
  shapeFile: any;
  tag: any;
  tileLayer: any;
  tl: any;
  tools: any;
  useColorLog: any;
  videoProjection: any;
  vp: any;
  weather: any;
  webSocket: any;
  marker3d: any;
  reset: any;
  waterFlowField: any;
};
declare let HostConfig: {
  Manager: string;
  Player: string;
  Path: string;
  MatchServer: string;
  PlayerMapping: string;
};
declare let Color: any;
declare let BPFunctionData: any;
declare let BPFuncParamType: any;
declare let userInfo: any;
declare let Common_config: any;
declare let PolylineStyle: any;
declare const AMap: any;
declare const Polygon3DStyle: any;
